name             'metasploit'
maintainer       'cmluciano'
maintainer_email 'cmluciano@dragoon.io'
license          'All rights reserved'
description      'Installs/Configures chef-metasploit'
long_description 'Installs/Configures chef-metasploit'
version          '0.1.0'

depends 'apt'
depends 'rubies'
